const fs = require('fs');
let task = fs.readFileSync('C:/Users/zozoo/.gemini/antigravity/brain/ababa079-367a-4a6b-a1b5-9bb6d141af0b/task.md', 'utf8');
task = task.replace('- `[ ]` Modifier `EVA_V4_fixed_v4/js/features/cloudworks.js`', '- `[x]` Modifier `EVA_V4_fixed_v4/js/features/cloudworks.js`');
task = task.replace('- `[ ]` Modifier `eva-pc/web/js/features/cloudworks.js`', '- `[x]` Modifier `eva-pc/web/js/features/cloudworks.js`');
task = task.replace('- `[ ]` **2. Correction de CloudWorks**', '- `[x]` **2. Correction de CloudWorks**');
task = task.replace('- `[ ]` Ajouter `onDisconnect().update({ online: false })` dans `pc-agent.js`.', '- `[x]` Ajouter `onDisconnect().update({ online: false })` dans `pc-agent.js`.');
task = task.replace('- `[ ]` Intercepter `app.on(\'before-quit\')` dans `main.ts`', '- `[x]` Intercepter `app.on(\'before-quit\')` dans `main.ts`');
task = task.replace('- `[ ]` Envoyer `app:quit-ready` depuis le renderer', '- `[x]` Envoyer `app:quit-ready` depuis le renderer');
task = task.replace('- `[ ]` **3. Amélioration de la Déconnexion PC (Hors Ligne)**', '- `[x]` **3. Amélioration de la Déconnexion PC (Hors Ligne)**');
fs.writeFileSync('C:/Users/zozoo/.gemini/antigravity/brain/ababa079-367a-4a6b-a1b5-9bb6d141af0b/task.md', task, 'utf8');
